import type { SpamRule } from "../../types/spam";

export const rawSpamKeywords: SpamRule[] = [
  { reason: "spam acc", regex: /\bspam\s+acc\b/i, weight: 5, isStrongSignal: true },
  {
    reason: "block if you want",
    regex: /\bblock\s+if\s+you\s+want\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "my main", regex: /\bmy\s+main\b/i, weight: 3 },
  { reason: "follow my main", regex: /\bfollow\s+my\s+main\b/i, weight: 5, isStrongSignal: true },
  { reason: "follow main", regex: /\bfollow\s+main\b/i, weight: 5, isStrongSignal: true },
  { reason: "main @", regex: /\bmain\s*@[a-z\d-]+\b/i, weight: 4, isStrongSignal: true },
  { reason: "my main @", regex: /\bmy\s+main\s*@[a-z\d-]+\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "follow for follow",
    regex: /\bfollow\s+for\s+follow\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "follow 4 follow", regex: /\bfollow\s*4\s*follow\b/i, weight: 4, isStrongSignal: true },
  { reason: "f4f", regex: /\bf4f\b/i, weight: 4, isStrongSignal: true },
  { reason: "follow back", regex: /\bfollow\s+back\b/i, weight: 3 },
  { reason: "i follow back", regex: /\bi\s+follow\s+back\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "i will follow back",
    regex: /\bi\s+will\s+follow\s+back\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  {
    reason: "block if unwanted",
    regex: /\bblock\s+if\s+unwanted\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "spam follower", regex: /\bspam\s+follower\b/i, weight: 5, isStrongSignal: true },
  {
    reason: "spam follow account",
    regex: /\bspam\s+follow\s+account\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "block if you uncomfortable",
    regex: /\bblock\s+if\s+you\s+uncomfortable\b/i,
    weight: 4,
  },
  {
    reason: "block if you are uncomfortable",
    regex: /\bblock\s+if\s+you\s+are\s+uncomfortable\b/i,
    weight: 4,
  },
  { reason: "sb to remove", regex: /\bsb\s+to\s+remove\b/i, weight: 5, isStrongSignal: true },
  { reason: "remove me", regex: /\bremove\s+me\b/i, weight: 3 },
  { reason: "unfollow me", regex: /\bunfollow\s+me\b/i, weight: 3 },
  { reason: "star for star", regex: /\bstar\s+for\s+star\b/i, weight: 4, isStrongSignal: true },
  { reason: "star 4 star", regex: /\bstar\s*4\s*star\b/i, weight: 4, isStrongSignal: true },
  { reason: "s4s", regex: /\bs4s\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "i will star back",
    regex: /\bi\s+will\s+star\s+back\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  {
    reason: "star my repo and i will star yours",
    regex: /\bstar\s+my\s+repo\b.*\bi\s+will\s+star\s+yours\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  { reason: "star my repos", regex: /\bstar\s+my\s+repos\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "star my repositories",
    regex: /\bstar\s+my\s+repositories\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  {
    reason: "please star my repository",
    regex: /\bplease\s+star\s+my\s+repository\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  {
    reason: "kindly star my repo",
    regex: /\bkindly\s+star\s+my\s+repo\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "support me with a star", regex: /\bsupport\s+me\s+with\s+a\s+star\b/i, weight: 3 },
  {
    reason: "give me stars to my repositories and back to your repositories",
    regex: /\bgive\s+me\s+stars\b.*\brepositories\b.*\bback\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "following people for fun, I'm not some creep.",
    regex: /\bfollowing\s+people\s+for\s+fun\b.*\bnot\s+some\s+creep\b/i,
    weight: 4,
  },
  {
    reason:
      "Check my repository I am sure you will find interesting projects etc and kindly star the repos",
    regex: /\bcheck\s+my\s+repository\b.*\bkindly\s+star\s+the\s+repos\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  { reason: "block permanent", regex: /\bblock\s+permanent\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "block if you find this account annoying",
    regex: /\bblock\s+if\s+you\s+find\s+this\s+account\s+annoying\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "block permanently",
    regex: /\bblock\s+permanently\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "Check my repos", regex: /\bcheck\s+my\s+repos\b/i, weight: 3 },
  { reason: "Check my repositories", regex: /\bcheck\s+my\s+repositories\b/i, weight: 3 },
  { reason: "check out my github", regex: /\bcheck\s+out\s+my\s+github\b/i, weight: 3 },
  { reason: "visit my profile", regex: /\bvisit\s+my\s+profile\b/i, weight: 3 },
  { reason: "visit my repo", regex: /\bvisit\s+my\s+repo\b/i, weight: 3 },
  {
    reason: "check link in bio",
    regex: /\bcheck\s+link\s+in\s+bio\b/i,
    weight: 4,
    isStrongSignal: true,
  },
  { reason: "boost your github profile", regex: /\bboost\s+your\s+github\s+profile\b/i, weight: 3 },
  { reason: "increase github followers", regex: /\bincrease\s+github\s+followers\b/i, weight: 4 },
  { reason: "increase github stars", regex: /\bincrease\s+github\s+stars\b/i, weight: 4 },
  { reason: "follow bot", regex: /\bfollow\s+bot\b/i, weight: 5, isStrongSignal: true },
  { reason: "bot account", regex: /\bbot\s+account\b/i, weight: 5, isStrongSignal: true },
  { reason: "automated follow", regex: /\bautomated\s+follow\b/i, weight: 5, isStrongSignal: true },
  {
    reason: "dm me on telegram",
    regex: /\bdm\s+me\s+on\s+telegram\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "contact me on whatsapp",
    regex: /\bcontact\s+me\s+on\s+whatsapp\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "message me on discord",
    regex: /\bmessage\s+me\s+on\s+discord\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  { reason: "marketing services", regex: /\bmarketing\s+services\b/i, weight: 3 },
  { reason: "smm service", regex: /\bsmm\s+service\b/i, weight: 3 },
  { reason: "seo services", regex: /\bseo\s+services\b/i, weight: 3 },
  { reason: "crypto airdrop", regex: /\bcrypto\s+airdrop\b/i, weight: 4, isStrongSignal: true },
  { reason: "web3 giveaway", regex: /\bweb3\s+giveaway\b/i, weight: 4, isStrongSignal: true },
  { reason: "nft drop", regex: /\bnft\s+drop\b/i, weight: 4, isStrongSignal: true },
  {
    reason: "if u follow me, i will follow u 2",
    regex: /\bif\s+u\s+follow\s+me\b.*\bi\s+will\s+follow\s+u\s*2\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "follow me and i will follow you back",
    regex: /\bfollow\s+me\b.*\bi\s+will\s+follow\s+you\s+back\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  {
    reason: "Please follow and give me star.",
    regex: /\bplease\s+follow\b.*\bgive\s+me\s+star\b/i,
    weight: 5,
    isStrongSignal: true,
  },
  { reason: "Please follow", regex: /\bplease\s+follow\b/i, weight: 3 },
];
